# Generated by Django 4.2.16 on 2024-10-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='valor_venda',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='custo_producao',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0.0),
        ),
    ]
