# Generated by Django 4.2.16 on 2024-10-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_produto_valor_venda_alter_produto_custo_producao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='custo_producao',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.FloatField(),
        ),
    ]
